version: '3.8'

services:
  node:
    image: node:20-alpine
    restart: always
    ports:
      - 3000:3000
    command: /bin/sh -c "cd /var/www && npm run start:dev"
    volumes:
      - ./:/var/www
  mysql:
    image: mysql:8.0.42
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 3333:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
